name: Move-Code-To-Deploy-PROD
on:
  push:
    branches:
      - 'main'
    paths:
      - 'dags/**'
      - 'utils/**'
      - 'sql/**'
      - 'plugins/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'dags/**'
      - 'utils/**'
      - 'sql/**'
      - 'plugins/**'
  workflow_dispatch:

jobs:  
  Move-Code-To-Deploy-PROD:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4         
        with:
          fetch-depth: 2 
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: 1Find Difference between branch and commit
        id: Finddiff        
        run: |
          DIFF_CONTENT=$(git diff --name-status ${{ github.event.before }} ${{ github.sha }} | xargs)
          echo "fileswithdepth=$DIFF_CONTENT" >> $GITHUB_OUTPUT
        shell: bash

      - name: 2get changed files
        id: getfile
        run: |
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)
          echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: 2echo output
        run: |
          echo "Changed files: ${{ steps.getfile.outputs.files }}" 
        
      - name: Move the files to temp directory
        id: Movefiles    
        run: |        
          echo "Files in previous versus current version: ${{ steps.Finddiff.outputs.fileswithdepth }} "    
          mkdir -p temp_dags/{utils,plugins,sql}  
          myarray="${{ steps.Finddiff.outputs.fileswithdepth }}"
          changelist=(${myarray// / })
          len=${#changelist[@]}
          echo "${myarray} has ${len} elements"    
          for ((i=0; i<${len}; i++)) ; do
            case "${changelist[$i]}" in
              A | M | C | T | "R100" )
                if [ "${changelist[$i]}" = "R100" ]; then  
                  change_file="${changelist[$i+2]}"
                  file_path=$(dirname "${changelist[$i+2]}")
                  file_name=$(basename "${changelist[$i+2]}")
                else
                  change_file="${changelist[$i+1]}"
                  file_path=$(dirname "${changelist[$i+1]}")
                  file_name=$(basename "${changelist[$i+1]}") 
                fi
                IFS='/'
                read -a root <<< "${file_path}"
                echo "${file_path} and ${file_name} with root as ${root[0]}"
                case  "${root[0]}" in 
                  "dags") 
                    echo "  > DAG loop:${file_path}/${file_name}."   
                    cp "${change_file}" temp_dags/ 
                    ;;
                  sql | utils) 
                    echo "  > OUT loop:${file_path}/${file_name}." 
                    mkdir -p temp_dags/${file_path}  
                    cp --parents "${change_file}" "temp_dags"   
                    echo "file temp_dags/${file_path} created"
                    ;; 
                esac
                ;;
              R | D)
                echo "-- ${changelist[$i+1]} no action done. "
                ;;
              esac
          done
          
          ls -R temp_dags/
        
      - name: Upload S3
        id: upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION}}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PROD }}   
          DEVOPS_DIR: devops 
          directory: "temp_dags"
        run: |
          pip install boto3
          python ${{ env.DEVOPS_DIR }}/upload_content_to_s3.py
