name: Move-Code-To-Deploy-PROD

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'dags/**'
      - 'utils/**'
      - 'sql/**'
      - 'plugins/**'
  workflow_dispatch:

jobs:
  Move-Code-To-Deploy-PROD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Changed to 0 to ensure git diff works

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: 1Find Difference between branch and commit
        id: Finddiff
        run: |
          # Updated to use $GITHUB_OUTPUT instead of deprecated ::set-output
          DIFF=$(git diff --name-status ${{ github.event.before }} ${{ github.sha }} | xargs)
          echo "fileswithdepth=$DIFF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Move the files to temp directory
        id: Movefiles
        run: |
          echo "Files: ${{ steps.Finddiff.outputs.fileswithdepth }}"
          mkdir -p temp_dags/utils temp_dags/plugins temp_dags/sql
          
          myarray="${{ steps.Finddiff.outputs.fileswithdepth }}"
          changelist=(${myarray// / })
          len=${#changelist[@]}
          
          for ((i=0; i<${len}; i++)) ; do
            case "${changelist[$i]}" in
              A | M | C | T | "R100" )
                if [ "${changelist[$i]}" = "R100" ]; then
                  change_file="${changelist[$i+2]}"
                else
                  change_file="${changelist[$i+1]}"
                fi
                
                file_path=$(dirname "$change_file")
                root=$(echo "$file_path" | cut -d'/' -f1)
                
                case "$root" in
                  "dags")
                    cp "$change_file" temp_dags/
                    ;;
                  "sql" | "utils")
                    mkdir -p "temp_dags/$file_path"
                    cp "$change_file" "temp_dags/$change_file"
                    ;;
                esac
                ;;
            esac
          done
          ls -R temp_dags/

      - name: Upload S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PROD }}
          DEVOPS_DIR: devops
        run: |
          python ${{ env.DEVOPS_DIR }}/upload_content_to_s3.py
