name: Move-Code-To-Deploy-PROD

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'dags/**'
      - 'sql/**'
  workflow_dispatch:

jobs:
  Move-Code-To-Deploy-PROD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetches all history so git diff can compare branches

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Calculate Changed Files
        id: diff
        run: |
          # Compare the current state (HEAD) with the target branch (origin/main)
          FILES=$(git diff --name-status origin/main HEAD | xargs)
          echo "fileswithdepth=$FILES" >> $GITHUB_OUTPUT
        shell: bash

      - name: Move files to temp directory
        run: |
          mkdir -p temp_dags
          
          # Convert the string of files into an array
          IFS=' ' read -r -a changelist <<< "${{ steps.diff.outputs.fileswithdepth }}"
          
          for ((i=0; i<${#changelist[@]}; i++)); do
            case "${changelist[$i]}" in
              A|M|C|T|R100)
                # Determine file path based on status
                if [ "${changelist[$i]}" = "R100" ]; then
                  file="${changelist[$i+2]}"
                  i=$((i+2)) # Skip ahead
                else
                  file="${changelist[$i+1]}"
                  i=$((i+1))
                fi

                # Only copy if file exists and is in monitored directories
                if [[ "$file" == dags/* ]] || [[ "$file" == sql/* ]] || [[ "$file" == utils/* ]]; then
                  echo "Copying $file to temp_dags/"
                  mkdir -p "temp_dags/$(dirname "$file")"
                  cp "$file" "temp_dags/$file"
                fi
                ;;
            esac
          done

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_PROD }}
        run: |
          pip install boto3
          python devops/upload_content_to_s3.py
